-- =====================================================================
-- TABLA DE AUDITORÍA DE SESIONES
-- Requerida por el Keycloak User Storage SPI para registrar logins
-- =====================================================================

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='SGTM_AUDITORIA_SESIONES' AND xtype='U')
BEGIN
    CREATE TABLE ESEGURIDAD.SGTM_AUDITORIA_SESIONES (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        USUARIO NVARCHAR(255) NOT NULL,
        SESION_UUID NVARCHAR(255) NOT NULL,
        INICIO_SESION DATETIME NOT NULL,
        FIN_SESION DATETIME NULL,
        DIRECCION_IP NVARCHAR(50) NULL,
        HOSTNAME NVARCHAR(255) NULL,
        TIPO_INICIO NVARCHAR(50) NOT NULL DEFAULT 'ROPC',
        TIPO_CIERRE NVARCHAR(50) NULL,
        LOGIN_EXITOSO BIT NOT NULL DEFAULT 1,
        MOTIVO_FALLO NVARCHAR(500) NULL,
        CREADOPOR NVARCHAR(255) NULL,
        FECHACREACION DATETIME NOT NULL DEFAULT GETDATE()
    );

    CREATE INDEX IX_AUDITORIA_SESIONES_USUARIO ON ESEGURIDAD.SGTM_AUDITORIA_SESIONES(USUARIO);
    CREATE INDEX IX_AUDITORIA_SESIONES_UUID ON ESEGURIDAD.SGTM_AUDITORIA_SESIONES(SESION_UUID);
    CREATE INDEX IX_AUDITORIA_SESIONES_FECHA ON ESEGURIDAD.SGTM_AUDITORIA_SESIONES(FECHACREACION);

    PRINT 'Tabla SGTM_AUDITORIA_SESIONES creada exitosamente';
END
ELSE
BEGIN
    PRINT 'La tabla SGTM_AUDITORIA_SESIONES ya existe';
END
GO
